name: Update Version

on:
  push:
    branches:
      - main

jobs:
  update_version:
    name: Update Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: true
      
      - name: Update version
        id: version_bumper
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Update version in package.json without creating a git tag/commit
          npm version patch --no-git-tag-version
          
          # Extract new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

          # Update version in app.json
          # Using node to avoid jq dependency, assuming a simple structure
          node -e "                                                                                                   
            const fs = require('fs');
            const appJsonPath = './app.json';
            const appJson = require(appJsonPath);
            appJson.expo.version = '$NEW_VERSION';
            fs.writeFileSync(appJsonPath, JSON.stringify(appJson, null, 2));
          "
      
      - name: Commit and Push changes
        run: |
          git add app.json package.json
          git commit -m "chore(release): bump version to ${{ steps.version_bumper.outputs.new_version }}"
          git push
